version: '3.8'
services:
  doc:
    build:
      context: ./
      dockerfile: ./html_page/Dockerfile
    volumes:
     - ./html_page:/html_page
     - ./documentation:/documentation

  web:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./html_page:/usr/share/nginx/html
