global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
  - job_name: 'airflow-webserver'
    static_configs:
      - targets: ['airflow-webserver:8080']
