version: '3.8'
services:
  web:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./page/index.html:/usr/share/nginx/html/index.html
      - ./documentation/documentation.html:/usr/share/nginx/html/documentation/documentation.html