tg_channels = {
    "moscowach": True,
    "tinkoff_analytics_official": True,
    "novosti_efir": True,
    "novosti_voinaa": True,
    "bbbreaking": True,
    "moscowmap": True,
    "readovkanews": True,
    "mash": True,
    "rian_ru": True,
    "varlamov_news": True,
    "meduzalive": True,
    "lentach": True,
    "rt_russian": True,
    "tjournal": True,
    "vzglyad_ru": True,
    "roscosmos_gk": True,
    "rbc_news": True,
}
