name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file test_app/pom.xml

    - name: Run server in the background
      run: java -cp test_app/target/socket-app-1.0-SNAPSHOT-jar-with-dependencies.jar SocketServer &
      shell: bash

    - name: Run client
      run: |
        echo "Starting client..."
        sleep 5 # Wait for server to start
        java -cp test_app/target/socket-app-1.0-SNAPSHOT-jar-with-dependencies.jar SocketClient
