name: Docker build, run, test FastAPI and upload artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_run_tests_and_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: build
        run: docker compose -f docker-compose.html_page.yaml -f docker-compose.FastAPI.yaml -f docker-compose.airflow.yaml -f docker-compose.mlflow_minio.yaml --env-file ./env/.env.airflow --env-file ./env/.env.mlflow --env-file ./env/.env.minio build
      - name: run
        run: docker compose -f docker-compose.html_page.yaml -f docker-compose.FastAPI.yaml -f docker-compose.airflow.yaml -f docker-compose.mlflow_minio.yaml --env-file ./env/.env.airflow --env-file ./env/.env.mlflow --env-file ./env/.env.minio up -d
      - name: running tests FastAPI
        run: docker exec mlops_pipeline-app-1 pytest test_main.py
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation_html
          path: html_page/index.html
      - name: stop
        run: docker compose -f docker-compose.html_page.yaml -f docker-compose.FastAPI.yaml -f docker-compose.airflow.yaml -f docker-compose.mlflow_minio.yaml --env-file ./env/.env.airflow --env-file ./env/.env.mlflow --env-file ./env/.env.minio down
