name: Docker build, run, tests and upload artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_run_tests_and_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: build
        run: docker compose -f docker-compose.html_page.yaml -f docker-compose.FastAPI.yaml -f docker-compose.airflow.yaml -f docker-compose.mlflow_minio.yaml --env-file ./env/.env.airflow --env-file ./env/.env.mlflow --env-file ./env/.env.minio build
      - name: run
        run: docker compose -f docker-compose.html_page.yaml -f docker-compose.FastAPI.yaml -f docker-compose.airflow.yaml -f docker-compose.mlflow_minio.yaml --env-file ./env/.env.airflow --env-file ./env/.env.mlflow --env-file ./env/.env.minio up -d
      
      - name: install requirements 
        run: pip install -U pyrogram psycopg2 requests minio
        
      - name: running tests FastAPI
        run:  docker exec mlops_pipeline-app-1 pytest test_main.py
      
      - name: running tests Telegram bot
        run: python3 -m unittest tests/test_telegram_utils.py -v

      - name: running tests airflow dag
        run: python3 -m unittest tests/test_dag.py -v

      - name: running tests minio
        run: python3 -m unittest tests/test_minio.py -v

      - name: running tests mlflow
        run: python3 -m unittest tests/test_mlflow.py -v

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation_html
          path: |
            html_page/index.html
            html_page/styles.css
            html_page/images
      - name: stop
        run: docker compose -f docker-compose.html_page.yaml -f docker-compose.FastAPI.yaml -f docker-compose.airflow.yaml -f docker-compose.mlflow_minio.yaml --env-file ./env/.env.airflow --env-file ./env/.env.mlflow --env-file ./env/.env.minio down
